added shebangs

diff --git a/code/shellscript/security/ssh-send-key b/code/shellscript/security/ssh-send-key
--- a/code/shellscript/security/ssh-send-key
+++ b/code/shellscript/security/ssh-send-key
@@ -7,16 +7,19 @@ then
 fi
 
 # KEYFILE="$HOME/.ssh/id_rsa.pub"
-KEYFILE="$HOME/.ssh/id_dsa.pub"
+[ ! -f "$KEYFILE" ] && KEYFILE="$HOME/.ssh/id_dsa.pub"
 
 if [ ! -f "$KEYFILE" ]
 then
 	echo "You have no ssh key $KEYFILE, would you like me to generate one?"
 	read ANSWER
-	if [ "$ANSWER" = y ]
+	if [ "$ANSWER" = y ] || [ "$ANSWER" = yes ]
 	then
 		mkdir -p "$HOME/.ssh"
 		ssh-keygen -t dsa -f "$HOME/.ssh/id_dsa" -N ""
+	else
+		echo "I cannot send a key since you don't have one, pleaase export KEYFILE."
+		exit 1
 	fi
 fi
 
@@ -48,7 +51,7 @@ exit
 # cat .ssh/id_rsa.pub |
 cat .ssh/id_dsa.pub |
 
-ssh-agent verbosely ssh "$1" eval "cat >> ./.ssh/authorized_keys"
+ssh-agent verbosely ssh "$@" eval "cat >> ./.ssh/authorized_keys"
 
 ## Paste the key into your local authorized_keys
 # eg. using on localhost: cat >> ~/.ssh/authorized_keys
